const tagList = [
    'electronic',
    'bomba',
    'home',
    'kitchen',
    'furniture',
    'smartphone',
    'laptop',
    'headphones',
    'wearable',
    'gadget',
    'men',
    'women',
    'kids',
    'summer',
    'winter',
    'appliances',
    'decor',
    'cookware',
    'utensils',
    'storage',
    'sports',
    'outdoor',
    'fitness',
    'beauty',
    'skincare',
    'organic',
    'sustainable',
    'luxury',
    'budget',
    'premium',
    'new',
    'sale',
    'bestseller',
    'limited'
];

module.exports = tagList;
